// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYDC3rWBfc_elKv-kGo196FMLdfmUWQfM',
    appId: '1:368728282112:web:de2cee04b273d066fa74e5',
    messagingSenderId: '368728282112',
    projectId: 'todoapp-91669',
    authDomain: 'todoapp-91669.firebaseapp.com',
    storageBucket: 'todoapp-91669.firebasestorage.app',
    measurementId: 'G-MCLVCZWXC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbgPWsaeIRFtJ2poDRhZTFzli4htVl0VY',
    appId: '1:368728282112:android:28d005344232cbb7fa74e5',
    messagingSenderId: '368728282112',
    projectId: 'todoapp-91669',
    storageBucket: 'todoapp-91669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJ240KjRCJOy2-cR0FnkfHfud0XMhJXI',
    appId: '1:368728282112:ios:6bfbda8d3d166889fa74e5',
    messagingSenderId: '368728282112',
    projectId: 'todoapp-91669',
    storageBucket: 'todoapp-91669.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJ240KjRCJOy2-cR0FnkfHfud0XMhJXI',
    appId: '1:368728282112:ios:6bfbda8d3d166889fa74e5',
    messagingSenderId: '368728282112',
    projectId: 'todoapp-91669',
    storageBucket: 'todoapp-91669.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYDC3rWBfc_elKv-kGo196FMLdfmUWQfM',
    appId: '1:368728282112:web:b3be77a3bf30cccbfa74e5',
    messagingSenderId: '368728282112',
    projectId: 'todoapp-91669',
    authDomain: 'todoapp-91669.firebaseapp.com',
    storageBucket: 'todoapp-91669.firebasestorage.app',
    measurementId: 'G-8KYE1MFNEV',
  );
}
